### ISSUE TITLE
Please add how to use windows

### ISSUE THREAD

**Issue by rebornishard** [joakim-eriksson/nb-eslint#21]
can't use this one for windows, please add how to

thanks

**Comment by Chris2011** [comment]
Will have a look later.

**Comment by Chris2011** [comment]
@rebornishard Is there more information, that you can provide? Unfortunately it is not really helpful. I use windows and everything works fine. Do you have problems/exceptions?

**Comment by Chris2011** [comment]
So in short:
* Install eslint globally
* Download latest version (1.3.0 - need build first)
* Go to options -> HTML5/ESLint
* Click on search to find the eslint cli
* Let the other options as it is
* Open your project, which has an eslint config file.
* If you don't have an eslint config file, in your project, due to eslint is not a dependency in your project, you need to go to the options and provide an eslint config file by your own.
